### ISSUE TITLE
[NEW OSS PROJECT]: sigstore

### ISSUE THREAD

**Issue by cpanato** [pulumi/team-edition-for-open-source#1]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

sigstore

### What's your GitHub organization or repository?

https://github.com/sigstore

### What's Pulumi.com team ID?

sigstore

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes
not for now but in a near future yes for some best practices and other things that we can do

**Comment by rawkode** [comment]
All sorted.

**Comment by cpanato** [comment]
thank you!
