### ISSUE TITLE
[NEW OSS PROJECT]: Shabad OS

### ISSUE THREAD

**Issue by Harjot1Singh** [pulumi/team-edition-for-open-source#11]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Shabad OS

### What's your GitHub organization or repository?

https://github.com/ShabadOS

### What's Pulumi.com team ID?

ShabadOS

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by Harjot1Singh** [comment]
Yep!

**Comment by aaronkao** [comment]
@Harjot1Singh ShabadOS is approved for a 1 year subscription of Team Edition for Open Source. please make a pull request to add your Pulumi code to the README of this repo. thanks
