### ISSUE TITLE
[NEW OSS PROJECT]: Virtual Finland Development

### ISSUE THREAD

**Issue by lsipii** [pulumi/team-edition-for-open-source#13]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Virtual Finland Development

### What's your GitHub organization or repository?

https://github.com/Virtual-Finland-Development

### What's Pulumi.com team ID?

virtualfinland

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by lsipii** [comment]
> The main Pulumi code we should link to is here right? https://github.com/Virtual-Finland-Development/infrastructure

Sounds about right: most (if not all) of the VFD-organization projects depend on the Pulumi tools. The infrastructure code repository project is a "root project" where other projects rely on and as such could be considered the main.

**Comment by aaronkao** [comment]
Sounds great. Will let you know when access is granted.

**Comment by aaronkao** [comment]
@lsipii ok, you are approved for a 1 year subscription of Team Edition for Open Source. Please make a pull request to add your org to the README.
