### ISSUE TITLE
[NEW OSS PROJECT]: OpenTTD

### ISSUE THREAD

**Issue by TrueBrain** [pulumi/team-edition-for-open-source#14]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

OpenTTD

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/OpenTTD/infra

### What's Pulumi.com team ID?

OpenTTD

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by aaronkao** [comment]
You now have 1 year of Team Edition. Please make a pull request to add your project to the README. Thanks
