### ISSUE TITLE
[NEW OSS PROJECT]: Postman.gov.sg

### ISSUE THREAD

**Issue by tan-zx** [pulumi/team-edition-for-open-source#16]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Postman.gov.sg

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/opengovsg/postmangovsg-infra

### What's Pulumi.com team ID?

postmansg

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by aaronkao** [comment]
The github repo 404s. Is that a private repo?

**Comment by tan-zx** [comment]
apologies, have made it public
