### ISSUE TITLE
[NEW OSS PROJECT]: FormSG

### ISSUE THREAD

**Issue by LinHuiqing** [pulumi/team-edition-for-open-source#17]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

FormSG

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/opengovsg/formsg-infra

### What's Pulumi.com team ID?

FormSG

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by aaronkao** [comment]
https://github.com/opengovsg/formsg-infra This is 404ing

**Comment by LinHuiqing** [comment]
Sorry about that - it should work now! Thanks for the prompt response 👍

**Comment by aaronkao** [comment]
You now have a 1 year subscription of Team Edition.
