### ISSUE TITLE
[NEW OSS PROJECT]: Drupal

### ISSUE THREAD

**Issue by nnewton** [pulumi/team-edition-for-open-source#2]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Drupal

### What's your GitHub organization or repository?

https://git.drupalcode.org/project/drupal

### What's Pulumi.com team ID?

drupalassociation

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by nnewton** [comment]
Hi All, 

I just wanted to checkin on this and see if I filled this out correctly/if you needed anything from me or the DA. Thanks.

**Comment by rawkode** [comment]
@nnewton You did. Apologies, I'm waiting on our internal team responding to my request. I'll follow up today

**Comment by nnewton** [comment]
Awesome! Thank you!
