### ISSUE TITLE
[NEW OSS PROJECT]: HackerCamp

### ISSUE THREAD

**Issue by rarous** [pulumi/team-edition-for-open-source#22]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Hacker Camp

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/hackercampcz/core

### What's Pulumi.com team ID?

hackercamp

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [x] Yes

**Comment by aaronkao** [comment]
Changing your billing to enable Team Edition for {hackercamp}
