### ISSUE TITLE
[NEW OSS PROJECT]: nf-core

### ISSUE THREAD

**Issue by edmundmiller** [pulumi/team-edition-for-open-source#25]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

nf-core

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/nf-core/

### What's Pulumi.com team ID?

 nf-core

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [X] Yes

**Comment by aaronkao** [comment]
Can you specifically point me at the repo that has the Pulumi code. We will link to that specific repo.

**Comment by edmundmiller** [comment]
Sure thing! @aaronkao https://github.com/nf-core/ops

**Comment by edmundmiller** [comment]
Hey, just bumping this. Any updates?

**Comment by aaronkao** [comment]
@edmundmiller hey this in progress right now. if you need help now, hit me up on Community Slack.

**Comment by aaronkao** [comment]
@edmundmiller you should be good to go. Let me know if you need anything else

**Comment by edmundmiller** [comment]
Awesome, thank you so much!
