### ISSUE TITLE
[NEW OSS PROJECT]: requesting Pulumi open source team edition for our open source suite of infectious disease modeling tools

### ISSUE THREAD

**Issue by bsweger** [pulumi/team-edition-for-open-source#26]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Community Engineer from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Hubverse (https://hubdocs.readthedocs.io/en/latest/)

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/Infectious-Disease-Modeling-Hubs/hubverse-infrastructure

### What's Pulumi.com team ID?

hubverse

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by bsweger** [comment]
Thank you for considering the Hubverse for Pulumi's open source license. The Hubverse provides a suite of open-source tools used by teams around the world to create "hubs" that collect team forecasts related to infectious diseases (e.g., COVID, RSV, flu).

The main Hubverse documentation is here: https://hubdocs.readthedocs.io/en/latest/

We're currently in the process of transitioning our hub submissions, data transformations, and data storage to AWS and have recently completed a trial of Pulumi to use as our IaC. We decided to move forward with Pulumi, hence the license request.

Please let me know if you have any other questions!

**Comment by aaronkao** [comment]
This is great. Let me submit a ticket internally to get Team Edition enabled.

**Comment by aaronkao** [comment]
@bsweger sorry for the delay, this should be enabled. let me know if its not so.

**Comment by bsweger** [comment]
@aaronkao Confirmed that it's enabled--thank you, we really appreciate it!
