### ISSUE TITLE
[NEW OSS PROJECT]: Tabiya Taxonomy-model-application

### ISSUE THREAD

**Issue by ApostolosBenisis** [pulumi/team-edition-for-open-source#29]
### Are you a maintainer, or core-contributor, to the project?

- [x] Yes

### We already have a Pulumi.com account?

- [x] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Community Engineer from the Pulumi team?

- [x] Yes

### What's your Open Source project called?

taxonomy-model-application

### Where is the GitHub repo where your organization's infra code is located?

https://github.com/tabiya-tech/taxonomy-model-application

### What's your Pulumi.com organization ID?

tabiya-tech

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by ApostolosBenisis** [comment]
You can find the pulumi code here: 
[https://github.com/tabiya-tech/taxonomy-model-application/tree/main/iac
](https://github.com/tabiya-tech/taxonomy-model-application/tree/main/iac)

**Comment by aaronkao** [comment]
hey, hit me up on Slack to reach me quickly. But yes, this looks good. Let me get ops to turn it on for you. Sorry for the delay
