### ISSUE TITLE
[NEW OSS PROJECT]: Rawkode Academy

### ISSUE THREAD

**Issue by rawkode** [pulumi/team-edition-for-open-source#3]
### Are you a maintainer, or core-contributor, to the project?

- [X] Yes

### We already have a Pulumi.com account?

- [X] Yes, we have created an account

### Do you agree to regular check-ins, no more than once every 90 days, with a Developer Advocate from the Pulumi team?

- [X] Yes

### What's your Open Source project called?

Rawkode Academy

### What's your GitHub organization or repository?

https://github.com/rawkode-academy

### What's Pulumi.com team ID?

rawkode-academy

### Do/would you like any assistance with your Pulumi adoption from the DevRel team?

- [ ] Yes

**Comment by aaronkao** [comment]
Closing out because its not currently being used.
